<a href="https://colab.research.google.com/github/artjow/-AI-/blob/main/%EC%8A%A4%EC%B9%BC%EB%9D%BC%2C%EB%B2%A1%ED%84%B0_%EB%A7%A4%ED%8A%B8%EB%A6%ADipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#스칼라는 0차원
import numpy as np
x = np.array(1)
x.ndim

0

In [11]:
# 1차원 벡터
x = np.array([1,2,3,4,5])
x.ndim

1

In [12]:
# matrix는 vector의 집합
# ndim 은 배열이 몇 차 배열인지를 알려준다.

x=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
x.ndim

2

In [13]:
'''tensor란 matrix의 집합 
따라서 tensor는 3차원 부터 시작
'''
x=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[7,8,9]]])
print(x)
x.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]


3

In [ ]:
1. Tensor는 배열의 집합이다.
2. 차원의 수는 Rank와 같은말이다